# Site Settings
title: MughniMind | Can't Close My Mind
email: ac.mughni@gmail.com
description: Some text about your blog.
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: mughnimind
user_description: Didn't I told you that I can't write much.
disqus_username: acemughnie

# Social Media
# Remove the item if you don't need it
github_username: mughnimind
# facebook_username: facebook_username
 twitter_username: acemughnie
instagram_username: acemughnie
# linkedin_username: linkedin_username
# medium_username: acemughnie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Beranda
    url: /
  - title: Tentang
    url: /about/
  - title: Kontak
    url: /contact/
  - title: Tagar
    url: /tags/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
